/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Bookings: () => import('#controllers/bookings_controller'),
  Coaches: () => import('#controllers/coaches_controller'),
  Courts: () => import('#controllers/courts_controller'),
  Customers: () => import('#controllers/customers_controller'),
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Payments: () => import('#controllers/payments_controller'),
  Session: () => import('#controllers/session_controller'),
}
