/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  AdminSession: () => import('#controllers/admin_session_controller'),
  admin: {
    Bookings: () => import('#controllers/admin/bookings_controller'),
    CoachReports: () => import('#controllers/admin/coach_reports_controller'),
    Courts: () => import('#controllers/admin/courts_controller'),
    Payments: () => import('#controllers/admin/payments_controller'),
    Profile: () => import('#controllers/admin/profile_controller'),
    Reports: () => import('#controllers/admin/reports_controller'),
    Settings: () => import('#controllers/admin/settings_controller'),
    Slips: () => import('#controllers/admin/slips_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  Bookings: () => import('#controllers/bookings_controller'),
  Coaches: () => import('#controllers/coaches_controller'),
  Courts: () => import('#controllers/courts_controller'),
  Customers: () => import('#controllers/customers_controller'),
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Payments: () => import('#controllers/payments_controller'),
  Session: () => import('#controllers/session_controller'),
}
