/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookingSchema extends BaseModel {
  static $columns = ['bookingCoachPrice', 'bookingCourtPrice', 'bookingDate', 'bookingEnd', 'bookingId', 'bookingStart', 'bookingStatus', 'courtId', 'createdAt', 'customerId', 'scheduleId', 'totalPrice', 'updatedAt'] as const
  $columns = BookingSchema.$columns
  @column()
  declare bookingCoachPrice: string | null
  @column()
  declare bookingCourtPrice: string | null
  @column.date()
  declare bookingDate: DateTime | null
  @column()
  declare bookingEnd: string | null
  @column({ isPrimary: true })
  declare bookingId: number
  @column()
  declare bookingStart: string | null
  @column()
  declare bookingStatus: string | null
  @column()
  declare courtId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerId: number | null
  @column()
  declare scheduleId: number | null
  @column()
  declare totalPrice: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CoachPricingSchema extends BaseModel {
  static $columns = ['coachLevelDesc', 'coachLevelId', 'coachPrice', 'createdAt', 'updatedAt'] as const
  $columns = CoachPricingSchema.$columns
  @column()
  declare coachLevelDesc: string | null
  @column({ isPrimary: true })
  declare coachLevelId: number
  @column()
  declare coachPrice: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CoachScheduleSchema extends BaseModel {
  static $columns = ['availDate', 'coachId', 'createdAt', 'endTime', 'scheduleId', 'startTime', 'updatedAt'] as const
  $columns = CoachScheduleSchema.$columns
  @column.date()
  declare availDate: DateTime | null
  @column()
  declare coachId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare endTime: string | null
  @column({ isPrimary: true })
  declare scheduleId: number
  @column()
  declare startTime: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CoachSchema extends BaseModel {
  static $columns = ['coachId', 'coachLevelId', 'coachName', 'coachStatus', 'createdAt', 'updatedAt'] as const
  $columns = CoachSchema.$columns
  @column({ isPrimary: true })
  declare coachId: number
  @column()
  declare coachLevelId: number | null
  @column()
  declare coachName: string | null
  @column()
  declare coachStatus: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourtSchema extends BaseModel {
  static $columns = ['courtId', 'courtName', 'courtPricePerHr', 'courtStatus', 'createdAt', 'updatedAt'] as const
  $columns = CourtSchema.$columns
  @column({ isPrimary: true })
  declare courtId: number
  @column()
  declare courtName: string | null
  @column()
  declare courtPricePerHr: string | null
  @column()
  declare courtStatus: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['createdAt', 'customerEmail', 'customerId', 'customerName', 'customerPhone', 'customerType', 'tierId', 'updatedAt', 'userId'] as const
  $columns = CustomerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerEmail: string | null
  @column({ isPrimary: true })
  declare customerId: number
  @column()
  declare customerName: string
  @column()
  declare customerPhone: string
  @column()
  declare customerType: string | null
  @column()
  declare tierId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amount', 'bookingId', 'createdAt', 'paymentId', 'paymentMethod', 'paymentStatus', 'paymentTime', 'paymentType', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amount: string | null
  @column()
  declare bookingId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare paymentId: number
  @column()
  declare paymentMethod: string | null
  @column()
  declare paymentStatus: string | null
  @column.dateTime()
  declare paymentTime: DateTime | null
  @column()
  declare paymentType: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TierSchema extends BaseModel {
  static $columns = ['createdAt', 'minHours', 'tierDesc', 'tierDiscount', 'tierId', 'updatedAt'] as const
  $columns = TierSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare minHours: number | null
  @column()
  declare tierDesc: string | null
  @column()
  declare tierDiscount: number | null
  @column({ isPrimary: true })
  declare tierId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}
